In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
test_df = pd.read_csv('/content/drive/My Drive/Data/Capstone/test.csv')
train_df = pd.read_csv('/content/drive/My Drive/Data/Capstone/train.csv')
BTS_df = pd.read_csv('/content/drive/My Drive/Data/Capstone/BTS_Data.csv')

In [5]:
test_df.describe()

       Battery_Capacity_kWh  Discount_Percentage
count            275.000000           275.000000
mean              69.440000             8.541818
std               17.122334             5.717903
min               40.000000             0.000000
25%               56.000000             4.000000
50%               69.000000             8.000000
75%               83.500000            14.000000
max              100.000000            20.000000

In [6]:
train_df.describe()

       Battery_Capacity_kWh  Discount_Percentage  Units_Sold       Revenue
count            531.000000           531.000000  531.000000  5.310000e+02
mean              69.408663             9.013183  227.881356  4.918762e+06
std               17.627504             5.966085   97.905957  2.661565e+06
min               40.000000             0.000000   50.000000  8.170320e+05
25%               53.000000             3.000000  147.000000  2.944326e+06
50%               70.000000             8.000000  234.000000  4.575344e+06
75%               84.000000            14.000000  313.500000  6.469173e+06
max              100.000000            20.000000  398.000000  3.016229e+07

In [7]:
BTS_df.describe()

,"Table 1-19: Hybrid-Electric, Plug-in Hybrid-Electric, and Electric Vehicle Sales",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
count,10,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
unique,10,3,3,3,3,3,3,3,3,3,...,4,4,4,4,4,4,4,4,4,4
top,Hybrid electric,Z,Z,Z,Z,Z,Z,Z,Z,Z,...,2015,2016,2017,2018,2019,2020,2021,2022,(R) 2023,2024
freq,1,2,2,2,2,2,2,2,2,2,...,1,1,1,1,1,1,1,1,1,1

In [8]:
test_df.info()
train_df.info()
BTS_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  275 non-null    object
 1   Region                275 non-null    object
 2   Brand                 275 non-null    object
 3   Model                 275 non-null    object
 4   Vehicle_Type          275 non-null    object
 5   Battery_Capacity_kWh  275 non-null    int64
 6   Discount_Percentage   275 non-null    int64
 7   Customer_Segment      275 non-null    object
 8   Fast_Charging_Option  275 non-null    object
dtypes: int64(2), object(7)
memory usage: 19.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 531 entries, 0 to 530
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  531 non-null    object
 1   Region                531 non-null    object
 2   Brand                 531 non-null    object
 3   Model                 531 non-null    object
 4   Vehicle_Type          531 non-null    object
 5   Battery_Capacity_kWh  531 non-null    int64
 6   Discount_Percentage   531 non-null    int64
 7   Customer_Segment      531 non-null    object
 8   Fast_Charging_Option  531 non-null    object
 9   Units_Sold            531 non-null    int64
 10  Revenue               531 non-null    int64
dtypes: int64(4), object(7)
memory usage: 45.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 26 columns):
 #   Column                                                                             Non-Null Count  Dtype
---  ------                                                                             --------------  -----
 0   Table 1-19:  Hybrid-Electric, Plug-in Hybrid-Electric, and Electric Vehicle Sales  10 non-null     object
 1   Unnamed: 1                                                                         4 non-null      object
 2   Unnamed: 2                                                                         4 non-null      object
 3   Unnamed: 3                                                                         4 non-null      object
 4   Unnamed: 4                                                                         4 non-null      object
 5   Unnamed: 5                                                                         4 non-null      object
 6   Unnamed: 6                                                                         4 non-null      object
 7   Unnamed: 7                                                                         4 non-null      object
 8   Unnamed: 8                                                                         4 non-null      object
 9   Unnamed: 9                                                                         4 non-null      object
 10  Unnamed: 10                                                                        4 non-null      object
 11  Unnamed: 11                                                                        4 non-null      object
 12  Unnamed: 12                                                                        4 non-null      object
 13  Unnamed: 13                                                                        4 non-null      object
 14  Unnamed: 14                                                                        4 non-null      object
 15  Unnamed: 15                                                                        4 non-null      object
 16  Unnamed: 16                                                                        4 non-null      object
 17  Unnamed: 17                                                                        4 non-null      object
 18  Unnamed: 18                                                                        4 non-null      object
 19  Unnamed: 19                                                                        4 non-null      object
 20  Unnamed: 20                                                                        4 non-null      object
 21  Unnamed: 21                                                                        4 non-null      object
 22  Unnamed: 22                                                                        4 non-null      object
 23  Unnamed: 23                                                                        4 non-null      object
 24  Unnamed: 24                                                                        4 non-null      object
 25  Unnamed: 25                                                                        4 non-null      object
dtypes: object(26)
memory usage: 2.8+ KB

In [10]:
print(test_df.dtypes)

Date                    object
Region                  object
Brand                   object
Model                   object
Vehicle_Type            object
Battery_Capacity_kWh     int64
Discount_Percentage      int64
Customer_Segment        object
Fast_Charging_Option    object
dtype: object

In [11]:
print(train_df.dtypes)

Date                    object
Region                  object
Brand                   object
Model                   object
Vehicle_Type            object
Battery_Capacity_kWh     int64
Discount_Percentage      int64
Customer_Segment        object
Fast_Charging_Option    object
Units_Sold               int64
Revenue                  int64
dtype: object

In [12]:
print(BTS_df.dtypes)

Table 1-19:  Hybrid-Electric, Plug-in Hybrid-Electric, and Electric Vehicle Sales    object
Unnamed: 1                                                                           object
Unnamed: 2                                                                           object
Unnamed: 3                                                                           object
Unnamed: 4                                                                           object
Unnamed: 5                                                                           object
Unnamed: 6                                                                           object
Unnamed: 7                                                                           object
Unnamed: 8                                                                           object
Unnamed: 9                                                                           object
Unnamed: 10                                                                          object
Unnamed: 11                                                                          object
Unnamed: 12                                                                          object
Unnamed: 13                                                                          object
Unnamed: 14                                                                          object
Unnamed: 15                                                                          object
Unnamed: 16                                                                          object
Unnamed: 17                                                                          object
Unnamed: 18                                                                          object
Unnamed: 19                                                                          object
Unnamed: 20                                                                          object
Unnamed: 21                                                                          object
Unnamed: 22                                                                          object
Unnamed: 23                                                                          object
Unnamed: 24                                                                          object
Unnamed: 25                                                                          object
dtype: object

In [14]:
test_df.head()

,Date,Region,Brand,Model,Vehicle_Type,Battery_Capacity_kWh,Discount_Percentage,Customer_Segment,Fast_Charging_Option
0,2023-04,Oceania,Volkswagen,Model 3,SUV,45,16,Budget Conscious,No
1,2023-10,Oceania,Ford,Model 3,Sedan,89,5,Tech Enthusiast,Yes
2,2023-10,South America,Volkswagen,Atto 3,Sedan,61,4,Budget Conscious,Yes
3,2023-02,Africa,Volkswagen,Corolla EV,Crossover,100,16,Eco-Conscious,No
4,2023-10,North America,Tesla,Rio EV,Sedan,70,8,Eco-Conscious,Yes

In [17]:
test_df['Date'] = pd.to_datetime(test_df['Date'], format = "%Y-%m")
print(test_df.dtypes)

Date                    datetime64[ns]
Region                          object
Brand                           object
Model                           object
Vehicle_Type                    object
Battery_Capacity_kWh             int64
Discount_Percentage              int64
Customer_Segment                object
Fast_Charging_Option            object
dtype: object

In [18]:
train_df['Date'] = pd.to_datetime(train_df['Date'], format = "%Y-%m")
print(train_df.dtypes)

Date                    datetime64[ns]
Region                          object
Brand                           object
Model                           object
Vehicle_Type                    object
Battery_Capacity_kWh             int64
Discount_Percentage              int64
Customer_Segment                object
Fast_Charging_Option            object
Units_Sold                       int64
Revenue                          int64
dtype: object

In [20]:
import pandas as pd

bts_updated = {
    "Year": [2010, 2011, 2012, 2013, 2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024],
    "Hybrid Electric": [274684, 268749, 434648, 495535, 452172, 384400, 346949, 370680,338149, 399444, 455067, 799046, 766412, 1175456, 1609035],
    "Plug-in Hybrid Electric": [326, 7671, 38584, 49008, 55357, 43008, 72885, 91188, 123883, 85791, 69049, 176117, 183422, 293578, 321774],
    "Electric": [19, 10092, 14587, 48094, 63525, 71064, 86731, 104487, 207062, 233822, 238540, 459474, 747982, 1164638, 1247656]
}

bts_df = pd.DataFrame(bts_updated)

print(bts_df)

    Year  Hybrid Electric  Plug-in Hybrid Electric  Electric
0   2010           274684                      326        19
1   2011           268749                     7671     10092
2   2012           434648                    38584     14587
3   2013           495535                    49008     48094
4   2014           452172                    55357     63525
5   2015           384400                    43008     71064
6   2016           346949                    72885     86731
7   2017           370680                    91188    104487
8   2018           338149                   123883    207062
9   2019           399444                    85791    233822
10  2020           455067                    69049    238540
11  2021           799046                   176117    459474
12  2022           766412                   183422    747982
13  2023          1175456                   293578   1164638
14  2024          1609035                   321774   1247656

In [24]:
display(test_df.isnull().sum())

Date                    0
Region                  0
Brand                   0
Model                   0
Vehicle_Type            0
Battery_Capacity_kWh    0
Discount_Percentage     0
Customer_Segment        0
Fast_Charging_Option    0
dtype: int64

In [25]:
display(train_df.isnull().sum())

Date                    0
Region                  0
Brand                   0
Model                   0
Vehicle_Type            0
Battery_Capacity_kWh    0
Discount_Percentage     0
Customer_Segment        0
Fast_Charging_Option    0
Units_Sold              0
Revenue                 0
dtype: int64

In [26]:
display(bts_df.isnull().sum())

Year                       0
Hybrid Electric            0
Plug-in Hybrid Electric    0
Electric                   0
dtype: int64

In [31]:
bts_df.to_csv('/content/drive/My Drive/Data/Capstone/bts_data.csv', index=False)